### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by tavgar** [CalfCrusher/Poiana#5]
I'm getting this issue when I try to run the script:
` * Starting tor network..
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/connection.py", line 1063, in _connection_for_default_port
    return stem.socket.ControlPort(address, 9151)
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 503, in __init__
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Poiana/poiana.py", line 143, in <module>
    main()
  File "/home/kali/Poiana/poiana.py", line 138, in main
    stem()
  File "/home/kali/Poiana/poiana.py", line 76, in stem
    with Controller.from_port() as controller:
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/control.py", line 1031, in from_port
    control_port = stem.connection._connection_for_default_port(address)
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/connection.py", line 1065, in _connection_for_default_port
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/connection.py", line 1060, in _connection_for_default_port
    return stem.socket.ControlPort(address, 9051)
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 503, in __init__
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python3.10/dist-packages/stem-1.8.0-py3.10.egg/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused
`

**Comment by tavgar** [comment]
Somehow after reinstalling TOR it worked and don't forget to run it as sudo

**Comment by CalfCrusher** [comment]
You don't need to be root to run my tool

**Comment by tavgar** [comment]
> You don't need to be root to run my tool

I'm getting an error when I run it without root
