### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'hostname'

### ISSUE THREAD

**Issue by Deathpoolxrs** [CalfCrusher/Poiana#7]
* Starting tor network..
 * Creating hidden service in /home/ubuntu/Poiana/hidden_service_data
Traceback (most recent call last):
  File "poiana.py", line 141, in <module>
    main()
  File "poiana.py", line 136, in main
    stem()
  File "poiana.py", line 91, in stem
    if result.hostname:
AttributeError: 'NoneType' object has no attribute 'hostname'

**Comment by cr4ck3r-byte** [comment]
Estoy en las mismas
